spring:
  flyway:
    locations: classpath:db/migration, classpath:db/seed/local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

decorator:
  datasource:
    p6spy:
      enabled: true

logging:
  level:
    p6spy: INFO
    org.springframework.security: DEBUG
