clients:
  user-service:
    base-url: http://user-service:8085

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:localhost}:5432/auth_db
    username: ${RDS_USERNAME:auth_user}
    password: ${RDS_PASSWORD:auth_pw}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  kafka:
    producer:
      batch-size: 20
      fixed-delay-ms: 1000
