decorator:
  datasource:
    p6spy:
      enabled: false

app:
  kafka:
    producer:
      batch-size: 20
      fixed-delay-ms: 1000

logging:
  level:
    p6spy: OFF
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    kafka: WARN
