-- auth_db schema (slim): auth-only tables
-- includes audit columns: created_at/updated_at/created_by/updated_by

CREATE TABLE permission (
                            permission_id integer NOT NULL,
                            permission_code character varying(100) NOT NULL,
                            permission_name character varying(200),
                            use_yn boolean NOT NULL DEFAULT true,
                            created_by bigint,
                            created_at timestamptz NOT NULL DEFAULT now(),
                            updated_by bigint,
                            updated_at timestamptz NOT NULL DEFAULT now());;

CREATE SEQUENCE permission_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;;

CREATE TABLE role (
                      role_id integer NOT NULL,
                      role_name character varying(200) NOT NULL,
                      use_yn boolean NOT NULL DEFAULT true,
                      created_by bigint,
                      created_at timestamptz NOT NULL DEFAULT now(),
                      updated_by bigint,
                      updated_at timestamptz NOT NULL DEFAULT now());;

CREATE TABLE role_permission_map (
                                     role_id integer NOT NULL,
                                     permission_id integer NOT NULL,
                                     created_at timestamptz NOT NULL DEFAULT now(),
                                     updated_at timestamptz NOT NULL DEFAULT now(),
                                     created_by bigint,
                                     updated_by bigint);;

ALTER TABLE role ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME role_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);;

CREATE TABLE user_role_map (
                               user_id bigint NOT NULL,
                               role_id integer NOT NULL,
                               created_at timestamptz NOT NULL DEFAULT now(),
                               updated_at timestamptz NOT NULL DEFAULT now(),
                               created_by bigint,
                               updated_by bigint);;

CREATE TABLE users (
                       user_id bigint NOT NULL,
                       email character varying(200) NOT NULL,
                       login_id character varying(100),
                       user_password character varying(400),
                       user_name character varying(100),
                       emp_no character varying(100),
                       pstn_name character varying(200),
                       tel character varying(100),
                       user_password_update_dt timestamp with time zone,
                       user_password_fail_cnt integer,
                       old1_user_password character varying(400),
                       use_yn boolean NOT NULL DEFAULT true,
                       created_by bigint,
                       created_at timestamptz NOT NULL DEFAULT now(),
                       updated_by bigint,
                       updated_at timestamptz NOT NULL DEFAULT now());;

ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);;

ALTER TABLE permission ALTER COLUMN permission_id SET DEFAULT nextval('permission_permission_id_seq'::regclass);;

ALTER TABLE permission
    ADD CONSTRAINT permission_permission_code_key UNIQUE (permission_code);;

ALTER TABLE permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (permission_id);;

ALTER TABLE role_permission_map
    ADD CONSTRAINT role_permission_map_pkey PRIMARY KEY (role_id, permission_id);;

ALTER TABLE role
    ADD CONSTRAINT role_pkey PRIMARY KEY (role_id);;

ALTER TABLE role
    ADD CONSTRAINT role_role_name_key UNIQUE (role_name);;

ALTER TABLE users
    ADD CONSTRAINT user_email_key UNIQUE (email);;

ALTER TABLE users
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);;

ALTER TABLE user_role_map
    ADD CONSTRAINT user_role_map_pkey PRIMARY KEY (user_id, role_id);;

ALTER TABLE role_permission_map
    ADD CONSTRAINT role_permission_map_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES permission(permission_id);;

ALTER TABLE role_permission_map
    ADD CONSTRAINT role_permission_map_role_id_fkey FOREIGN KEY (role_id) REFERENCES role(role_id);;

ALTER TABLE user_role_map
    ADD CONSTRAINT user_role_map_role_id_fkey FOREIGN KEY (role_id) REFERENCES role(role_id);;

ALTER TABLE user_role_map
    ADD CONSTRAINT user_role_map_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id);;

-- comments
COMMENT ON TABLE permission IS '테이블: permission';
COMMENT ON COLUMN permission.permission_id IS 'permission id';
COMMENT ON COLUMN permission.permission_code IS 'permission code';
COMMENT ON COLUMN permission.permission_name IS 'permission name';
COMMENT ON COLUMN permission.use_yn IS 'use yn';
COMMENT ON COLUMN permission.created_by IS 'created by';
COMMENT ON COLUMN permission.created_at IS 'created at';
COMMENT ON COLUMN permission.updated_by IS 'updated by';
COMMENT ON COLUMN permission.updated_at IS 'updated at';
COMMENT ON TABLE role IS '테이블: role';
COMMENT ON COLUMN role.role_id IS 'role id';
COMMENT ON COLUMN role.role_name IS 'role name';
COMMENT ON COLUMN role.use_yn IS 'use yn';
COMMENT ON COLUMN role.created_by IS 'created by';
COMMENT ON COLUMN role.created_at IS 'created at';
COMMENT ON COLUMN role.updated_by IS 'updated by';
COMMENT ON COLUMN role.updated_at IS 'updated at';
COMMENT ON TABLE role_permission_map IS '테이블: role_permission_map';
COMMENT ON COLUMN role_permission_map.role_id IS 'role id';
COMMENT ON COLUMN role_permission_map.permission_id IS 'permission id';
COMMENT ON COLUMN role_permission_map.created_at IS 'created at';
COMMENT ON COLUMN role_permission_map.updated_at IS 'updated at';
COMMENT ON COLUMN role_permission_map.created_by IS 'created by';
COMMENT ON COLUMN role_permission_map.updated_by IS 'updated by';
COMMENT ON TABLE user_role_map IS '테이블: user_role_map';
COMMENT ON COLUMN user_role_map.user_id IS 'user id';
COMMENT ON COLUMN user_role_map.role_id IS 'role id';
COMMENT ON COLUMN user_role_map.created_at IS 'created at';
COMMENT ON COLUMN user_role_map.updated_at IS 'updated at';
COMMENT ON COLUMN user_role_map.created_by IS 'created by';
COMMENT ON COLUMN user_role_map.updated_by IS 'updated by';
COMMENT ON TABLE users IS '테이블: users';
COMMENT ON COLUMN users.user_id IS 'user id';
COMMENT ON COLUMN users.email IS 'email';
COMMENT ON COLUMN users.login_id IS 'login id';
COMMENT ON COLUMN users.user_password IS 'user password';
COMMENT ON COLUMN users.user_name IS 'user name';
COMMENT ON COLUMN users.emp_no IS 'emp no';
COMMENT ON COLUMN users.pstn_name IS 'pstn name';
COMMENT ON COLUMN users.tel IS 'tel';
COMMENT ON COLUMN users.user_password_update_dt IS 'user password update dt';
COMMENT ON COLUMN users.user_password_fail_cnt IS 'user password fail cnt';
COMMENT ON COLUMN users.old1_user_password IS 'old1 user password';
COMMENT ON COLUMN users.use_yn IS 'use yn';
COMMENT ON COLUMN users.created_by IS 'created by';
COMMENT ON COLUMN users.created_at IS 'created at';
COMMENT ON COLUMN users.updated_by IS 'updated by';
COMMENT ON COLUMN users.updated_at IS 'updated at';
