-- =====================================================
-- user_db schema (user-service)
-- - 사용자 프로필/업무 정보 소유
-- - auth_user_id로 auth의 user_id(JWT sub)와 연결 (Unique)
-- - 인증용 컬럼(email/loginId/passwordHash/roles)은 두지 않는다.
-- =====================================================

create table users (
                       user_id      bigint generated by default as identity primary key,

    -- auth-service의 user_id(JWT sub)와 매핑되는 외부 식별자
                       auth_user_id bigint not null,

    -- 프로필/업무 정보(사용자가 수정/조회할 성격)
                       user_name    varchar(100),
                       emp_no       varchar(100),
                       pstn_name    varchar(200),
                       tel          varchar(100),

    -- 계정 상태(프로필 관점)
                       use_yn       boolean not null default true,

    -- audit
                       created_at   timestamp with time zone not null default now(),
                       created_by   bigint,
                       updated_at   timestamp with time zone not null default now(),
                       updated_by   bigint
);

comment on table users is '사용자 프로필(인증정보 제외)';
comment on column users.auth_user_id is 'auth.user_id(JWT sub) 매핑키';

create unique index ux_users_auth_user_id on users(auth_user_id);
create index ix_users_use_yn on users(use_yn);
