app:
  kafka:
    consumers:
      order-payment-saga-enabled: true
    producer:
      relay-enabled: true
      batch-size: 20
      fixed-delay-ms: 1000

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    kafka: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
