spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:localhost}:5432/product_db
    username: ${RDS_USERNAME:product_user}
    password: ${RDS_PASSWORD:product_pw}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  kafka:
    consumers:
      order-payment-saga-enabled: true
    producer:
      relay-enabled: true
      batch-size: 20
      fixed-delay-ms: 1000
