spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

app:
  kafka:
    consumers:
      order-payment-saga-enabled: true
      worker-id: ${HOSTNAME:order-service}
      claim-timeout-seconds: 300
    producer:
      relay-enabled: true
      batch-size: 20
      fixed-delay-ms: 1000
      worker-id: ${HOSTNAME:order-service}
      claim-timeout-seconds: 300
      max-retry-count: 5
      retry-delay-seconds: 30

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    kafka: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
