spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:localhost}:5432/order_db
    username: ${RDS_USERNAME:order_user}
    password: ${RDS_PASSWORD:order_pw}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

clients:
  product:
    base-url: http://product-service:8082/internal/products
  payment:
    base-url: http://payment-service:8084

app:
  kafka:
    consumers:
      order-payment-saga-enabled: true
    producer:
      relay-enabled: true
      batch-size: 20
      fixed-delay-ms: 1000
