-- =====================================================
-- auth_db schema (auth-service)
-- - 인증/인가 데이터(자격증명, 역할, 리프레시 토큰 등) 소유
-- - JWT sub = auth_user_credential.user_id
-- =====================================================

-- 1) Credential (로그인 식별자/비밀번호 해시)
create table auth_user_credential (
                                      user_id        bigint generated by default as identity primary key,
                                      email          varchar(200) not null unique,
                                      login_id       varchar(100) not null unique,
                                      password_hash  varchar(400) not null,
                                      enabled        boolean not null default true,
                                      created_at     timestamp with time zone not null default now(),
                                      updated_at     timestamp with time zone not null default now()
);

comment on table auth_user_credential is '인증용 자격증명(로그인ID/이메일/비번해시)';
comment on column auth_user_credential.user_id is 'auth user id (JWT sub)';
comment on column auth_user_credential.password_hash is 'argon2/bcrypt hash';
comment on column auth_user_credential.enabled is '로그인 허용 여부(비활성화 동기화용)';

create index ix_auth_user_credential_login_id on auth_user_credential(login_id);
create index ix_auth_user_credential_email on auth_user_credential(email);


-- 2) Role
create table role (
                      role_id     integer generated by default as identity primary key,
                      role_name   varchar(200) not null unique,
                      use_yn      boolean not null default true,
                      created_at  timestamp with time zone not null default now(),
                      updated_at  timestamp with time zone not null default now()
);

comment on table role is '권한(Role) 마스터';


-- 3) User-Role mapping
create table user_role_map (
                               user_id     bigint not null,
                               role_id     integer not null,
                               created_at  timestamp with time zone not null default now(),
                               updated_at  timestamp with time zone not null default now(),
                               primary key (user_id, role_id),
                               constraint fk_user_role_map_user
                                   foreign key (user_id) references auth_user_credential(user_id) on delete cascade,
                               constraint fk_user_role_map_role
                                   foreign key (role_id) references role(role_id) on delete restrict
);

comment on table user_role_map is '사용자-권한 매핑(auth 기준)';


-- 4) Refresh token (선택: 회전/폐기/재사용 탐지하려면 필요)
create table auth_refresh_token (
                                    refresh_token_id bigint generated by default as identity primary key,
                                    user_id          bigint not null,
                                    token_hash       varchar(600) not null unique,
                                    revoked_yn       boolean not null default false,
                                    expires_at       timestamp with time zone not null,
                                    created_at       timestamp with time zone not null default now(),
                                    updated_at       timestamp with time zone not null default now(),
                                    constraint fk_refresh_user
                                        foreign key (user_id) references auth_user_credential(user_id) on delete cascade
);

comment on table auth_refresh_token is '리프레시 토큰 저장(해시 권장)';
create index ix_auth_refresh_token_user_id on auth_refresh_token(user_id);
